


apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: a0528075188-dev
  name: 'kafka'
  annotations: {}
spec:
  selector:
    matchLabels:
      app: 'kafka'
  replicas: 1
  template:
    metadata:
      labels:
        app: 'kafka'
    spec:
      containers:
        - name: kafka-container
          image: >-
            'bitnami/kafka:3.7'
          ports:
            - containerPort: 9092
              protocol: TCP
          env: 
           - name: KAFKA_BROKER_ID
             value: 1
           - name: KAFKA_LISTENERS
             value: PLAINTEXT://:9092
           - name: KAFKA_ADVERTISED_LISTENERS
             value: PEXTLAINT://kafka:9092
           - name: ALLOW_PLAINTEXT_LISTENER
             value: yes
           

      imagePullSecrets: []
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  paused: false
