version: '3.8'

services:

  Retriever:
    image: shmuelblau/retriever:1
    container_name: Retriever
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - kafka

    environment:
       HOST: "kafka"
      
       
     
    command: [ "python" , "main.py"]
    networks:
      Models:



  zookeeper:
    image: 'bitnami/zookeeper:3.8'
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      Models:

  kafka:
    image: 'bitnami/kafka:3.7'
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
     

    depends_on:
      - zookeeper
    networks:
      Models:



  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKER_CONNECT: "kafka:9092"
    depends_on:
      - kafka
    networks:
      Models:



networks:
  
  Models: